🔧 chore(latest): latest

diff --git a/.config/taskfiles/install/Taskfile-python.yml b/.config/taskfiles/install/Taskfile-python.yml
--- a/.config/taskfiles/install/Taskfile-python.yml
+++ b/.config/taskfiles/install/Taskfile-python.yml
@@ -3,53 +3,57 @@ version: '3'
 
 tasks:
   pip:
+    deps:
+      - :install:software:python
+    vars:
+      INSTALL_RECORD:
+        sh: |
+          if [ -n "$RECORD_INSTALL" ]; then
+            mkdir -p local/slim
+            echo '{{.PACKAGE}}' >> local/slim/exe.txt
+            echo '{{.INSTALL_TASK}}' >> local/slim/install.txt
+          fi
     run: when_changed
     log:
       error: Failed to install pip3 package `{{.PACKAGE}}`
       start: Installing pip3 package `{{.PACKAGE}}`
       success: Installed pip3 package `{{.PACKAGE}}`
     cmds:
-      - task: :install:software:python
       - pip3 install {{.PACKAGE}}
     status:
       - type {{.PACKAGE}} > /dev/null
 
   pipx:
-    deps:
-      - :install:software:pipx
-    run: when_changed
-    log:
-      error: Failed to install `{{.PACKAGE}}` with pipx
-      start: Installing `{{.PACKAGE}}` with pipx
-      success: Successfully installed `{{.PACKAGE}}` with pipx
     cmds:
-      - pipx install {{.PACKAGE}}
-    status:
-      - type {{.PACKAGE}} > /dev/null
+      - task: :install:pipx:install
+        vars:
+          BIN_NAME: '{{.BIN_NAME}}'
+          INSTALL_TASK: '{{.INSTALL_TASK}}'
+          PACKAGE: '{{.PACKAGE}}'
 
   pytest:
-    run: once
     cmds:
-      - task: pip
-        vars:
-          PACKAGE: pytest
+      - task: :install:pipx:pytest
 
   pytest-cov:
-    run: once
     cmds:
-      - task: pip
-        vars:
-          PACKAGE: pytest-cov
+      - task: :install:pipx:pytest-cov
 
   requirements:
     run: once
     cmds:
       - task: :install:software:python
-      - task: requirements:poetry:prereqs
       - task: requirements:poetry
       - task: :{{if eq .REPOSITORY_TYPE "ansible"}}ansible:galaxy:requirements{{else}}donothing{{end}}
 
   requirements:poetry:
+    cmds:
+      - task: requirements:poetry:prereqs
+      - task: requirements:poetry:install
+    status:
+      - '[ ! -f pyproject.toml ]'
+
+  requirements:poetry:install:
     summary: |
       # Poetry Requirements
 
@@ -66,7 +70,10 @@ tasks:
       - poetry config virtualenvs.in-project true
       - |
         if [ -n "$PYPI_TOKEN" ]; then
-          poetry config pypi-token.pypi "$PYPI_TOKEN"
+          poetry config pypi-token.pypi "$PYPI_TOKEN" || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Failed to run `poetry config pypi-token.pypi`'
+          fi
         fi
       - |
         if [ -n "$GITLAB_CI" ]; then
@@ -74,7 +81,10 @@ tasks:
         fi
       - |
         if [ -n "$GITLAB_CI" ]; then
-          poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}"
+          poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}" || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Failed to run `poetry config http-basic.gitlab gitlab-ci-token`'
+          fi
         fi
       - |
         if [ -n "$AUTO_UPDATE_PIP_PACKAGES" ]; then
@@ -91,11 +101,10 @@ tasks:
         fi
     sources:
       - pyproject.toml
-    preconditions:
-      - sh: test -f pyproject.toml
-        msg: The `pyproject.toml` file is missing!
 
   requirements:poetry:prereqs:
+    tags:
+      - update
     vars:
       GCC5_MISSING_MESSAGE: |
         It looks like your system is missing gcc-5 but gcc is available. You might be prompted
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -22,7 +22,7 @@ tasks:
   ansible:
     deps:
       - :symlink:{{.REPOSITORY_SUBTYPE}}
-      - :install:python:requirements
+      - :install:pipx:ansible-lint
     desc: Lint Ansible projects using Ansible Lint
     hide: '{{ne .REPOSITORY_TYPE "ansible"}}'
     summary: |
@@ -46,7 +46,8 @@ tasks:
 
   any:
     deps:
-      - :install:python:requirements
+      - :install:pipx:blocklint
+      - :install:pipx:pre-commit-hooks
     desc: Generic linting of files for things like destroyed-symlinks, merge conflicts, etc.
     log:
       error: Errors were reported by the global linters for `{{.CLI_ARGS}}`
@@ -166,7 +167,6 @@ tasks:
       success: Hadolint reported no errors
     cmds:
       - |
-        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}all Dockerfiles{{end}} with a Hadolint Docker image'
         {{if .CLI_ARGS}}
           docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS | replace .PWD ""}}
         {{else}}
@@ -178,6 +178,25 @@ tasks:
   dockerfile:
     cmds:
       - task: docker
+
+  dockerfilelint:
+    deps:
+      - :install:npm:dockerfilelint
+    desc: Lint a Dockerfile with `dockerfilelint`
+    hide:
+      sh: '[ ! -f Dockerfile ]'
+    log:
+      error: '`dockerfilelint` reported errors'
+      start: Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}the project{{end}} with `dockerfilelint`
+      success: '`dockerfilelint` ran successfully and reported no errors'
+    cmds:
+      - |
+        {{if .CLI_ARGS}}
+          dockerfilelint {{.CLI_ARGS | replace .PWD ""}}
+        {{else}}
+          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name Dockerfile -o \
+            -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 dockerfilelint
+        {{end}}
 
   eslint:
     deps:
@@ -203,6 +222,22 @@ tasks:
       error: ESLint has detected errors that need to be addressed
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with ESLint
       success: Successfully passed the ESLint test (please still address warnings)
+    cmds:
+      - >
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+
+  eslint:staged:
+    deps:
+      - :install:modules:local
+      - :install:npm:eslint
+    desc: Lint only modified files with ESLint
+    env:
+      ESLINT_STAGED_ONLY: on
+    log:
+      error: Failed to lint modified files with ESLint
+      start: Linting modified files with ESLint
+      success: Successfully linted modified files with ESLint
     cmds:
       - >
         {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
@@ -240,13 +275,15 @@ tasks:
         done < "$ESLINT_TMP"
 
   go:
-    desc: Lint Go with all available Go linters
+    deps:
+      - :install:software:go
+      - :install:software:golangci-lint
+    desc: Lint Go with `golangci-lint`
     summary: |
       # Lint Go Files
 
-      This task will lint Go files with the following linters:
-
-      * [go]()
+      This task will lint Go files with `golangci-lint`. The configuration is
+      stored in `.config/golangci.yml` and uses a handful of linters.
 
       If you would like to skip linting the whole project and instead lint an
       individual file, then you can do so by passing the file path as a CLI
@@ -254,39 +291,12 @@ tasks:
 
       **Example linting individual file:**
       `task lint:go -- path/filename.go`
+    log:
+      error: Detected errors with `golangci-lint`
+      start: Linting with `golangci-lint`
+      success: Successfully completed linting with `golangci-lint`
     cmds:
-      - task: go:vet
-
-  go:vet:
-    deps:
-      - :install:software:go
-    summary: |
-      # Inspect with Go Vet
-
-      This task inspects the source code with `go vet`.
-
-      If you need to add flags to the command, you can specify them in
-      `blueprint.goVetFlags`. `goVetFlags` can also be set in upstream variable
-      sources but this lint command does not force the generation of the
-      `.variables.json` file. If it cannot read `goVetFlags` in the `.variables.json` file
-      (perhaps because it was not generated yet), it will read `.blueprint.goVetFlags`
-      from `package.json`.
-
-      If you would like to run `go vet` on a specific path then you can pass the path
-      in as a CLI argument.
-
-      **Example of running `go vet` on a specific path:**
-      `task lint:go:vet -- path/to/file.go`
-    vars:
-      GO_VET_FLAGS:
-        sh: |
-          if [ -f .variables.json ]; then
-            echo " $(jq -r '.goVetFlags' .variables.json)"
-          else
-            echo " $(jq -r '.blueprint.goVetFlags' package.json | sed 's/null//')"
-          fi
-    cmds:
-      - go vet{{.GO_VET_FLAGS}}{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}
+      - golangci-lint run -c .config/golangci.yml{{if .CLI_ARGS}}{{.CLI_ARGS}}{{end}}
 
   js:
     deps:
@@ -303,9 +313,8 @@ tasks:
 
   lint-staged:
     deps:
-      - :install:modules:global
       - :install:modules:local
-      - :install:python:requirements
+      - :install:npm:lint-staged
     log:
       error: Errors were encountered when validating the staged files
       start: Linting staged files
@@ -388,11 +397,16 @@ tasks:
       start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with Prettier
       success: Prettier successfully finished
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} || EXIT_CODE=$?
+        if [ -n "$EXIT_CODE" ]; then
+          .config/log warn 'Failed to lint with `{{.NPX_HANDLE}}prettier` - falling back to `prettier`'
+          prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+        fi
 
   python:
     deps:
-      - :install:python:requirements
+      - :install:pipx:flake8
     label: lint:python
     desc: Lint Python files using Flake8
     hide: '{{ne .REPOSITORY_TYPE "python"}}'
@@ -508,6 +522,24 @@ tasks:
           fi
         ignore_errors: true
 
+  spelling:markdown:
+    deps:
+      - :install:go:misspell
+    desc: Run `misspell` (a spell-checker) on all markdown files
+    log:
+      error: Encountered errors while running `misspell`
+      start: Running `misspell` spell-check
+      success: Successfully ran `misspell` with no errors reported
+    cmds:
+      - >
+        .config/log info 'If errors are found, you can auto-fix them by running `task fix:spelling:markdown`'
+        {{if .CLI_ARGS}}
+        misspell {{.CLI_ARGS}}
+        {{else}}
+        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.md' \)
+        -print0 | xargs -0 -r -n1 misspell
+        {{end}}
+
   spelling:staged:
     deps:
       - :install:npm:cspell
@@ -531,7 +563,7 @@ tasks:
 
   toml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Lint TOML files
 
@@ -573,7 +605,7 @@ tasks:
 
   xml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:pre-commit-hooks
     summary: |
       # Lint XML files
 
@@ -594,7 +626,7 @@ tasks:
 
   yaml:
     deps:
-      - :install:python:requirements
+      - :install:pipx:yamllint
     desc: Lint `.yml` files using YAML Lint
     summary: |
       # Lint YML files using YAML Lint
